// Copyright (C) 2025 quip.network
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Live smoke test: end-to-end BTC transfer from a QuipWallet on testnet.
//
// PERSISTENT STATE: every WOTS+ private key, vault id, and Arch/Bitcoin txid
// generated by this script is written to a state file (default
// `keys/smoke-wallet-<vaultId>.json`, or `--state-file <path>`). If the run
// times out or crashes mid-flow, re-run with `--resume <state-file>` to pick
// up exactly where it left off — no fresh wallets minted, no UTXOs stranded.
//
// Flow (each step is idempotent and skipped if already done in state):
//   1. Verify the deployer/owner Arch account is anchored (anchor it if not).
//   2. Generate two WOTS+ keypairs (current pq_owner + rotation target pq_next)
//      and persist them to disk.
//   3. Build & broadcast TX-A (4 outputs: wallet anchor, wallet non-anchor,
//      deployer fee-input, deployer change). Persist its txid.
//   4. Submit createWallet (anchor=TX-A:0); wait for readback.
//   5. Build the fee tx (single input from TX-A:2, NONE|ANYONECANPAY-signed,
//      not broadcast).
//   6. Build BtcTransferMessage, sign with WOTS+, submit btcTransfer Arch tx
//      with explicit ComputeBudget prefix. Persist Arch txid.
//   7. Poll for processed status -> recover Bitcoin txid the runtime broadcast.
//   8. Wait for that Bitcoin tx in mempool; verify a 1500-sat UTXO landed back
//      at the deployer P2TR (round-trip).
//
// Run (fresh): npx tsx scripts/smoke-btc-transfer.ts
// Run (resume): npx tsx scripts/smoke-btc-transfer.ts --resume <state-file>

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { dirname } from 'node:path'
import {
  RpcConnection,
  SanitizedMessageUtil,
  SignatureUtil,
  SystemInstruction,
  type Instruction as ArchInstruction,
  type Pubkey,
  type SanitizedMessage,
} from '@arch-network/arch-sdk'
import { secp256k1 } from '@noble/curves/secp256k1.js'
import { sha256 } from '@noble/hashes/sha2.js'
import { base58check as mkBase58check } from '@scure/base'
import * as btc from '@scure/btc-signer'
import { Signer as Bip322Signer } from 'bip322-js'
import {
  QuipArchClient,
  programIdFor,
  createVaultId,
  buildBtcTransferMessage,
} from '../src'
import { buildBtcTransferWithWinternitzInstruction } from '../src/instructions'
import type { ClassicalSigner } from '../src/client'
import type { Instruction, WinternitzPublicKey } from '../src/types'

const KEYPAIR_PATH = '/Users/quark/quip/quip-arch/keys/testnet_deployer.json'
const ARCH_RPC = 'https://rpc.testnet.arch.network'
const MEMPOOL_BASE = 'https://mempool.space/testnet4/api'
const CLI_BIN = '/Users/quark/quip/quip-arch/target/debug/quip-cli'
const STATE_DIR = '/Users/quark/quip/quip-arch/keys'

const ANCHOR_AMOUNT = 3000n
const NONANCHOR_AMOUNT = 3000n
const FEE_INPUT_AMOUNT = 5000n
const TXA_FEE = 1500n
const OWNER_ANCHOR_AMOUNT = 3000n
const OWNER_ANCHOR_TX_FEE = 500n
const TRANSFER_AMOUNT = 1500n // partial spend of the 3000-sat non-anchor UTXO

// =============================================================================
// State file
// =============================================================================

interface SerializedKeypair {
  privateKey: string
  publicSeed: string
  publicKeyHash: string
}

interface SmokeState {
  vaultId: string // bigint as decimal string
  pqCurrent: SerializedKeypair
  pqNext: SerializedKeypair
  // Phase outputs (set as the run progresses)
  fundingTxid?: string // TX-A Bitcoin txid (display-order hex)
  createWalletArchTxid?: string // Arch tx id of createWallet submission
  walletCreated?: boolean
  btcTransferArchTxid?: string
  bitcoinTxidDisplay?: string
  done?: boolean
}

function defaultStatePath(vaultIdStr: string): string {
  return `${STATE_DIR}/smoke-wallet-${vaultIdStr}.json`
}

function loadState(path: string): SmokeState {
  const raw = readFileSync(path, 'utf8')
  return JSON.parse(raw) as SmokeState
}

function saveState(state: SmokeState, path: string): void {
  if (!existsSync(dirname(path))) {
    mkdirSync(dirname(path), { recursive: true })
  }
  writeFileSync(path, JSON.stringify(state, null, 2) + '\n', { mode: 0o600 })
}

// =============================================================================
// Helpers
// =============================================================================

function toHex(u8: Uint8Array): string {
  return Array.from(u8, (b) => b.toString(16).padStart(2, '0')).join('')
}
function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16)
  return out
}

// arch-sdk-ts returns `proc.bitcoin_txid` as a 32-byte Uint8Array in display
// order (or as a JSON-deserialized object with numeric keys when passed
// through serialization). Older versions of the SDK returned an
// internal-order hex string; that's why this script's first version did
// `fromHex` + reverse. With 0.0.26 the field is bytes-in-display-order, so
// the correct conversion is hex-encode without reversal.
function bitcoinTxidToDisplayHex(value: unknown): string {
  if (typeof value === 'string') {
    return value.startsWith('0x') ? value.slice(2) : value
  }
  if (value instanceof Uint8Array) return toHex(value)
  if (value && typeof value === 'object') {
    const obj = value as Record<string, number>
    const len = Object.keys(obj).length
    const arr = new Uint8Array(len)
    for (let i = 0; i < len; i++) arr[i] = obj[i]
    return toHex(arr)
  }
  throw new Error(`unexpected bitcoin_txid shape: ${JSON.stringify(value)}`)
}

function loadDeployerSecret(): Uint8Array {
  const raw = JSON.parse(readFileSync(KEYPAIR_PATH, 'utf8')) as number[]
  return new Uint8Array(raw)
}

async function fetchUtxos(address: string) {
  const res = await fetch(`${MEMPOOL_BASE}/address/${address}/utxo`)
  if (!res.ok) throw new Error(`utxo fetch HTTP ${res.status}`)
  return (await res.json()) as Array<{
    txid: string
    vout: number
    value: number
    status: { confirmed: boolean }
  }>
}

async function broadcastTxOrIgnoreKnown(rawHex: string, expectedTxid: string): Promise<string> {
  const res = await fetch(`${MEMPOOL_BASE}/tx`, {
    method: 'POST',
    body: rawHex,
    headers: { 'content-type': 'text/plain' },
  })
  const body = await res.text()
  if (res.ok) return body
  // If the tx is already known to mempool/chain, treat as success.
  if (
    body.includes('already in block chain') ||
    body.includes('already in mempool') ||
    body.includes('txn-already-known')
  ) {
    return expectedTxid
  }
  throw new Error(`broadcast HTTP ${res.status}: ${body}`)
}

async function isInMempoolOrChain(txid: string): Promise<boolean> {
  try {
    const res = await fetch(`${MEMPOOL_BASE}/tx/${txid}`)
    return res.ok
  } catch {
    return false
  }
}

async function waitForMempool(txid: string, maxMs = 120_000): Promise<void> {
  const start = Date.now()
  while (Date.now() - start < maxMs) {
    if (await isInMempoolOrChain(txid)) return
    await new Promise((r) => setTimeout(r, 2000))
  }
  throw new Error(`mempool did not surface ${txid} within ${maxMs}ms`)
}

interface WotsKeypair {
  privateKey: Uint8Array
  publicSeed: Uint8Array
  publicKeyHash: Uint8Array
}

function genWotsKeypair(): WotsKeypair {
  const out = execSync(`${CLI_BIN} wots-gen`).toString('utf8').trim()
  const j = JSON.parse(out)
  return {
    privateKey: fromHex(j.private_key),
    publicSeed: fromHex(j.public_seed),
    publicKeyHash: fromHex(j.public_key_hash),
  }
}

function serializeKeypair(k: WotsKeypair): SerializedKeypair {
  return {
    privateKey: toHex(k.privateKey),
    publicSeed: toHex(k.publicSeed),
    publicKeyHash: toHex(k.publicKeyHash),
  }
}
function deserializeKeypair(s: SerializedKeypair): WotsKeypair {
  return {
    privateKey: fromHex(s.privateKey),
    publicSeed: fromHex(s.publicSeed),
    publicKeyHash: fromHex(s.publicKeyHash),
  }
}

function wotsSign(privateKey: Uint8Array, message: Uint8Array): Uint8Array {
  const cmd = `${CLI_BIN} wots-sign --private-key ${toHex(privateKey)} --message ${toHex(message)}`
  const out = execSync(cmd).toString('utf8').trim()
  const j = JSON.parse(out)
  return fromHex(j.signature_data)
}

function makeBip322Signer(secret: Uint8Array, p2trAddress: string, xOnly: Uint8Array): ClassicalSigner {
  const base58check = mkBase58check(sha256)
  const wifPayload = new Uint8Array(34)
  wifPayload[0] = 0xef // testnet
  wifPayload.set(secret, 1)
  wifPayload[33] = 0x01 // compressed
  const wif = base58check.encode(wifPayload)
  return {
    pubkey: xOnly,
    sign(messageHashUtf8) {
      const sigB64 = Bip322Signer.sign(wif, p2trAddress, messageHashUtf8)
      return Uint8Array.from(Buffer.from(sigB64 as string, 'base64'))
    },
  }
}

function archIxToQuipIx(archIx: {
  program_id: Uint8Array
  accounts: Array<{ pubkey: Uint8Array; is_signer: boolean; is_writable: boolean }>
  data: Uint8Array
}): Instruction {
  return {
    programId: archIx.program_id,
    accounts: archIx.accounts.map((a) => ({
      pubkey: a.pubkey,
      isSigner: a.is_signer,
      isWritable: a.is_writable,
    })),
    data: archIx.data,
  }
}

// =============================================================================
// Phases
// =============================================================================

interface Ctx {
  rpc: RpcConnection
  client: QuipArchClient
  secret: Uint8Array
  xOnly: Uint8Array
  bip322: ClassicalSigner
  deployerP2tr: { address?: string; script: Uint8Array }
  ownerBtcAddr: string
  walletPDA: Uint8Array
  walletBtcAddr: string
  vaultId: Uint8Array
  statePath: string
}

async function ensureOwnerAnchored(ctx: Ctx): Promise<void> {
  const info = await withRetry('readAccountInfo(owner)',
    () => ctx.rpc.readAccountInfo(ctx.xOnly as Pubkey))
  const isAnchored = info.utxo && !/^0+:0$/.test(info.utxo) && info.utxo.length > 0
  if (isAnchored) {
    console.log('owner already anchored at', info.utxo)
    return
  }
  console.log('owner not anchored — broadcasting anchor UTXO + Anchor instruction')

  const utxos = await fetchUtxos(ctx.deployerP2tr.address!)
  const sorted = [...utxos].sort((a, b) => b.value - a.value)
  const pick = sorted.find(
    (u) => BigInt(u.value) >= OWNER_ANCHOR_AMOUNT + OWNER_ANCHOR_TX_FEE
  )
  if (!pick) throw new Error('no deployer UTXO large enough for owner anchor')

  const inputValue = BigInt(pick.value)
  const change = inputValue - OWNER_ANCHOR_AMOUNT - OWNER_ANCHOR_TX_FEE
  const tx = new btc.Transaction()
  tx.addInput({
    txid: pick.txid,
    index: pick.vout,
    witnessUtxo: { script: ctx.deployerP2tr.script, amount: inputValue },
    tapInternalKey: ctx.xOnly,
  })
  tx.addOutputAddress(ctx.ownerBtcAddr, OWNER_ANCHOR_AMOUNT, btc.TEST_NETWORK)
  if (change > 546n) {
    tx.addOutputAddress(ctx.deployerP2tr.address!, change, btc.TEST_NETWORK)
  }
  tx.sign(ctx.secret)
  tx.finalize()
  const anchorTxid = await broadcastTxOrIgnoreKnown(tx.hex, tx.id)
  console.log('anchor funding broadcast:', anchorTxid)
  await waitForMempool(anchorTxid)
  console.log('anchor funding in mempool; sleeping 15s before submitting Anchor ix')
  await new Promise((r) => setTimeout(r, 15_000))

  const archIx = SystemInstruction.anchor(ctx.xOnly as Pubkey, anchorTxid, 0)
  const ix = archIxToQuipIx({
    program_id: archIx.program_id,
    accounts: archIx.accounts,
    data: archIx.data,
  })
  const rt = await ctx.client.buildTransaction(ix, [ctx.bip322])
  const txid = await withRetry('sendTransaction(anchor)', () => ctx.rpc.sendTransaction(rt))
  console.log('Anchor ix submitted:', txid)
  for (let i = 0; i < 30; i++) {
    await new Promise((r) => setTimeout(r, 2000))
    let refreshed
    try {
      refreshed = await ctx.rpc.readAccountInfo(ctx.xOnly as Pubkey)
    } catch {
      continue
    }
    if (refreshed.utxo && !/^0+:0$/.test(refreshed.utxo)) {
      console.log('owner now anchored at', refreshed.utxo)
      return
    }
  }
  throw new Error('owner anchor did not finalize within 60s')
}

async function ensureFunding(ctx: Ctx, state: SmokeState): Promise<void> {
  if (state.fundingTxid) {
    if (await isInMempoolOrChain(state.fundingTxid)) {
      console.log('funding TX-A already broadcast:', state.fundingTxid)
      return
    }
    // State recorded a txid but mempool doesn't see it — possibly evicted.
    // Drop the recorded txid and rebroadcast.
    console.warn('WARN: recorded funding txid not in mempool, will rebuild')
    state.fundingTxid = undefined
    saveState(state, ctx.statePath)
  }

  const totalNeeded = ANCHOR_AMOUNT + NONANCHOR_AMOUNT + FEE_INPUT_AMOUNT + TXA_FEE
  const utxos = await fetchUtxos(ctx.deployerP2tr.address!)
  const sorted = [...utxos].sort((a, b) => b.value - a.value)
  const pick = sorted.find((u) => BigInt(u.value) >= totalNeeded)
  if (!pick) {
    throw new Error(
      `no deployer UTXO with >= ${totalNeeded} sats (found ${sorted.map((u) => u.value).join(',')})`
    )
  }
  const inputValue = BigInt(pick.value)
  const change = inputValue - totalNeeded
  console.log(`picked deployer UTXO ${pick.txid}:${pick.vout} (${pick.value} sats); change=${change}`)

  const tx = new btc.Transaction()
  tx.addInput({
    txid: pick.txid,
    index: pick.vout,
    witnessUtxo: { script: ctx.deployerP2tr.script, amount: inputValue },
    tapInternalKey: ctx.xOnly,
  })
  tx.addOutputAddress(ctx.walletBtcAddr, ANCHOR_AMOUNT, btc.TEST_NETWORK)
  tx.addOutputAddress(ctx.walletBtcAddr, NONANCHOR_AMOUNT, btc.TEST_NETWORK)
  tx.addOutputAddress(ctx.deployerP2tr.address!, FEE_INPUT_AMOUNT, btc.TEST_NETWORK)
  if (change > 546n) {
    tx.addOutputAddress(ctx.deployerP2tr.address!, change, btc.TEST_NETWORK)
  }
  tx.sign(ctx.secret)
  tx.finalize()
  console.log('TX-A local txid:', tx.id, 'size:', tx.hex.length / 2, 'bytes')
  const broadcastId = await broadcastTxOrIgnoreKnown(tx.hex, tx.id)
  if (broadcastId !== tx.id) console.warn('WARN: txid mismatch')
  state.fundingTxid = broadcastId
  saveState(state, ctx.statePath)
  console.log('TX-A broadcast:', broadcastId, '(state saved)')
  console.log('confirming TX-A mempool visibility...')
  await waitForMempool(broadcastId)
  console.log('TX-A in mempool; sleeping 15s before Arch submit')
  await new Promise((r) => setTimeout(r, 15_000))
}

// Retry a flaky RPC call with exponential backoff. Arch testnet's public RPC
// frequently returns transient errors under load; we don't want a single 5xx
// to abort a multi-minute run.
async function withRetry<T>(label: string, fn: () => Promise<T>, attempts = 6): Promise<T> {
  let lastErr: unknown
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn()
    } catch (e) {
      lastErr = e
      const wait = 1000 * Math.pow(2, i)
      console.warn(`  [retry] ${label} failed (attempt ${i + 1}/${attempts}); waiting ${wait}ms`)
      await new Promise((r) => setTimeout(r, wait))
    }
  }
  throw lastErr
}

// Poll-friendly wrapper around getWallet that treats RPC errors as "not yet
// available". The SDK's getWallet has a .catch but errors still surface here
// — likely an arch-sdk-ts quirk where some RPC failures throw synchronously.
async function tryGetWallet(ctx: Ctx) {
  try {
    return await ctx.client.getWallet(ctx.xOnly, ctx.vaultId)
  } catch {
    return null
  }
}

async function ensureWalletCreated(ctx: Ctx, state: SmokeState): Promise<void> {
  // Check the chain first — source of truth.
  const existing = await tryGetWallet(ctx)
  if (existing) {
    if (!state.walletCreated) {
      state.walletCreated = true
      saveState(state, ctx.statePath)
    }
    console.log(
      'wallet already exists on-chain: pq_owner_seed=%s tx_count=%s',
      toHex(existing.pqOwner.publicSeed),
      existing.transactionCount.toString()
    )
    return
  }

  if (!state.createWalletArchTxid) {
    if (!state.fundingTxid) throw new Error('cannot create wallet: missing fundingTxid')
    const anchorUtxo = { txid: fromHex(state.fundingTxid), vout: 0 }
    const pqCurrent = deserializeKeypair(state.pqCurrent)

    console.log('submitting createWallet...')
    const created = await withRetry('createWallet', () =>
      ctx.client.createWallet({
        owner: ctx.bip322,
        vaultId: ctx.vaultId,
        pqOwner: { publicSeed: pqCurrent.publicSeed, publicKeyHash: pqCurrent.publicKeyHash },
        deposit: 10_000n, // wallet pays factory.transfer_fee out of its own balance
        walletUtxo: anchorUtxo,
      })
    )
    state.createWalletArchTxid = created.signature
    saveState(state, ctx.statePath)
    console.log('  tx signature:', created.signature, '(state saved)')
  } else {
    console.log('createWallet already submitted, polling for processing:', state.createWalletArchTxid)
  }

  console.log('waiting for createWallet to process (testnet can take minutes)...')
  for (let i = 0; i < 120; i++) {
    await new Promise((r) => setTimeout(r, 5_000))
    const w = await tryGetWallet(ctx)
    if (w) {
      state.walletCreated = true
      saveState(state, ctx.statePath)
      console.log(
        '  wallet readback: pq_owner_seed=%s tx_count=%s',
        toHex(w.pqOwner.publicSeed),
        w.transactionCount.toString()
      )
      return
    }
    if (i % 6 === 0) console.log(`  still waiting (${5 * i}s)`)
  }
  throw new Error('createWallet readback returned null after 10 min')
}

async function ensureBtcTransferSubmitted(ctx: Ctx, state: SmokeState): Promise<void> {
  if (state.btcTransferArchTxid) {
    console.log('btcTransfer Arch tx already submitted:', state.btcTransferArchTxid)
    return
  }
  if (!state.fundingTxid) throw new Error('cannot submit btcTransfer: missing fundingTxid')

  const pqCurrent = deserializeKeypair(state.pqCurrent)
  const pqNext = deserializeKeypair(state.pqNext)
  const nonAnchorUtxo = { txid: fromHex(state.fundingTxid), vout: 1 }
  const feeInputOutpoint = { txid: state.fundingTxid, vout: 2 }

  console.log('building feeTx (single-input NONE|ANYONECANPAY-signed tx, not broadcast)')
  const feeTx = new btc.Transaction({ allowUnknownOutputs: true })
  feeTx.addInput({
    txid: feeInputOutpoint.txid,
    index: feeInputOutpoint.vout,
    witnessUtxo: { script: ctx.deployerP2tr.script, amount: FEE_INPUT_AMOUNT },
    tapInternalKey: ctx.xOnly,
    sighashType: btc.SigHash.NONE_ANYONECANPAY,
  })
  feeTx.sign(ctx.secret, [btc.SigHash.NONE_ANYONECANPAY])
  feeTx.finalize()
  // toBytes vs extract: extract() rejects zero-output txs; the on-chain
  // program ignores outputs (processor.rs:765 only reads input[0]). The
  // canonical Rust impl `arch_sdk::prepare_fees` produces zero-output,
  // so toBytes(true,true) matches that wire format exactly.
  const feeTxBytes = feeTx.toBytes(true, true)
  console.log(`feeTx serialized: ${feeTxBytes.length} bytes`)

  // Round-trip recipient = deployer's own P2TR.
  const recipientScript = ctx.deployerP2tr.script

  const currentKey: WinternitzPublicKey = {
    publicSeed: pqCurrent.publicSeed,
    publicKeyHash: pqCurrent.publicKeyHash,
  }
  const nextKey: WinternitzPublicKey = {
    publicSeed: pqNext.publicSeed,
    publicKeyHash: pqNext.publicKeyHash,
  }
  const message = buildBtcTransferMessage(
    currentKey, nextKey, recipientScript, TRANSFER_AMOUNT, nonAnchorUtxo,
  )
  console.log(`BtcTransferMessage: ${message.length} bytes`)
  const signatureData = wotsSign(pqCurrent.privateKey, message)
  console.log(`WOTS+ signature: ${signatureData.length} bytes`)

  console.log('submitting btcTransfer (manual build with compute budget)...')
  const walletAddress = ctx.client.walletAddress(ctx.xOnly, ctx.vaultId)
  const quipBtcIx = buildBtcTransferWithWinternitzInstruction({
    programId: programIdFor('testnet'),
    factoryAddress: ctx.client.factoryAddress,
    walletAddress,
    payer: ctx.xOnly,
    vaultId: ctx.vaultId,
    pqNext: nextKey,
    amount: TRANSFER_AMOUNT,
    recipientScriptPubkey: recipientScript,
    feeTx: feeTxBytes,
    sourceUtxo: nonAnchorUtxo,
    signature: { signatureData },
  })
  const btcArchIx: ArchInstruction = {
    program_id: quipBtcIx.programId as Pubkey,
    accounts: quipBtcIx.accounts.map((a) => ({
      pubkey: a.pubkey as Pubkey,
      is_signer: a.isSigner,
      is_writable: a.isWritable,
    })),
    data: quipBtcIx.data,
  }
  // Hand-built ComputeBudget.SetComputeUnitLimit ix with the correct
  // base58-decoded program ID. arch-sdk-ts@0.0.26 ships a buggy raw-ASCII
  // value; see TO_INVESTIGATE.md.
  const COMPUTE_BUDGET_PROGRAM_ID = fromHex(
    '0306466fe5211732ffecadba72c39be7bc8ce5bbc5f7126b2c439b3a40000000'
  )
  // Arch testnet hard-caps per-tx CU at 1.4M; requesting more is silently
  // clamped. 1.4M is enough for WOTS+ verify + BTC tx assembly per the
  // Rust integration tests' WOTS_COMPUTE_BUDGET.
  const cuLimit = 1_400_000
  const cuData = new Uint8Array(8)
  new DataView(cuData.buffer).setUint32(0, 1, true) // discriminant: SetComputeUnitLimit
  new DataView(cuData.buffer).setUint32(4, cuLimit, true)
  const computeBudgetIx: ArchInstruction = {
    program_id: COMPUTE_BUDGET_PROGRAM_ID as Pubkey,
    accounts: [],
    data: cuData,
  }

  const blockhashHex = await withRetry('getBestBlockHash', () => ctx.rpc.getBestBlockHash())
  const clean = blockhashHex.startsWith('0x') ? blockhashHex.slice(2) : blockhashHex
  const blockhash = SystemInstruction.hexStringToUint8Array(clean)
  const msg = SanitizedMessageUtil.createSanitizedMessage(
    [computeBudgetIx, btcArchIx],
    ctx.xOnly as Pubkey,
    blockhash
  )
  if (typeof msg === 'number') {
    throw new Error(`createSanitizedMessage CompileError ${msg}`)
  }
  const hash = SanitizedMessageUtil.hash(msg as SanitizedMessage)
  const hashUtf8 = new TextDecoder().decode(hash)
  const sig = await Promise.resolve(ctx.bip322.sign(hashUtf8))
  const signatures = [SignatureUtil.adjustSignature(sig)]
  const archTxid = await withRetry('sendTransaction(btcTransfer)', () =>
    ctx.rpc.sendTransaction({
      version: 0,
      signatures,
      message: msg as SanitizedMessage,
    })
  )
  state.btcTransferArchTxid = archTxid
  saveState(state, ctx.statePath)
  console.log('  arch txid:', archTxid, '(state saved)')
}

async function waitForBtcTransferProcessed(ctx: Ctx, state: SmokeState): Promise<void> {
  if (state.bitcoinTxidDisplay) {
    console.log('bitcoin txid already recorded:', state.bitcoinTxidDisplay)
    return
  }
  if (!state.btcTransferArchTxid) throw new Error('no btcTransferArchTxid in state')

  console.log('polling for btcTransfer to process (testnet can take 5-10+ minutes)...')
  // Poll up to 30 minutes — testnet has been observed taking 15+ min under load.
  for (let i = 0; i < 360; i++) {
    await new Promise((r) => setTimeout(r, 5000))
    let proc
    try {
      proc = await ctx.rpc.getProcessedTransaction(state.btcTransferArchTxid)
    } catch {
      if (i % 12 === 0) console.log(`  still pending (${5 * i}s, RPC error)`)
      continue
    }
    if (!proc) {
      if (i % 12 === 0) console.log(`  still pending (${5 * i}s)`)
      continue
    }
    const statusStr = JSON.stringify(proc.status)
    if (statusStr.includes('failed') || statusStr.includes('Failed')) {
      console.log('  logs:')
      for (const l of proc.logs) console.log('   ', l)
      throw new Error(`btcTransfer tx failed: ${statusStr}`)
    }
    if (proc.bitcoin_txid) {
      state.bitcoinTxidDisplay = bitcoinTxidToDisplayHex(proc.bitcoin_txid)
      saveState(state, ctx.statePath)
      console.log('  bitcoin txid (display):', state.bitcoinTxidDisplay, '(state saved)')
      return
    }
    console.log('  processed but no bitcoin_txid; logs:')
    for (const l of proc.logs) console.log('   ', l)
    throw new Error('processed tx missing bitcoin_txid')
  }
  throw new Error('did not get bitcoin_txid from processed tx within 30 min')
}

async function verifyRoundTrip(ctx: Ctx, state: SmokeState): Promise<void> {
  if (!state.bitcoinTxidDisplay) throw new Error('no bitcoinTxidDisplay in state')
  const pqNext = deserializeKeypair(state.pqNext)

  const wallet = await withRetry('getWallet(post-transfer)', () =>
    ctx.client.getWallet(ctx.xOnly, ctx.vaultId)
  )
  if (!wallet) throw new Error('post-transfer getWallet returned null')
  console.log(
    '  wallet after: pq_owner_seed=%s tx_count=%s',
    toHex(wallet.pqOwner.publicSeed),
    wallet.transactionCount.toString()
  )
  if (toHex(wallet.pqOwner.publicSeed) !== toHex(pqNext.publicSeed)) {
    throw new Error(
      `pq_owner did not rotate: expected ${toHex(pqNext.publicSeed)} got ${toHex(wallet.pqOwner.publicSeed)}`
    )
  }
  if (wallet.transactionCount < 1n) {
    throw new Error(`transaction_count not incremented (got ${wallet.transactionCount})`)
  }

  console.log('waiting for composite Bitcoin tx in mempool...')
  await waitForMempool(state.bitcoinTxidDisplay, 180_000)
  console.log('Bitcoin tx visible in mempool')

  const postUtxos = await fetchUtxos(ctx.deployerP2tr.address!)
  const matched = postUtxos.find(
    (u) => u.txid === state.bitcoinTxidDisplay && BigInt(u.value) === TRANSFER_AMOUNT
  )
  if (!matched) {
    throw new Error(
      `did not find a ${TRANSFER_AMOUNT}-sat UTXO at deployer P2TR sourced from ${state.bitcoinTxidDisplay}`
    )
  }
  console.log(
    `round-trip confirmed: ${matched.value} sats at ${ctx.deployerP2tr.address} from ${matched.txid}:${matched.vout}`
  )
  state.done = true
  saveState(state, ctx.statePath)
}

// =============================================================================
// Args + main
// =============================================================================

function parseArgs() {
  const args = process.argv.slice(2)
  const idx = (k: string) => args.indexOf(k)
  return {
    resume: idx('--resume') >= 0 ? args[idx('--resume') + 1] : undefined,
    stateFile: idx('--state-file') >= 0 ? args[idx('--state-file') + 1] : undefined,
    vaultIdArg: idx('--vault-id') >= 0 ? args[idx('--vault-id') + 1] : undefined,
  }
}

async function main() {
  const flags = parseArgs()

  let state: SmokeState
  let statePath: string

  if (flags.resume) {
    statePath = flags.resume
    if (!existsSync(statePath)) throw new Error(`--resume file not found: ${statePath}`)
    state = loadState(statePath)
    console.log('RESUMING from', statePath)
    console.log('  vault id:', state.vaultId)
    if (state.done) {
      console.log('state already marks run as done; nothing to do.')
      return
    }
  } else {
    const vaultIdNum = flags.vaultIdArg ? BigInt(flags.vaultIdArg) : BigInt(Date.now())
    statePath = flags.stateFile ?? defaultStatePath(vaultIdNum.toString())
    if (existsSync(statePath)) {
      throw new Error(
        `state file already exists at ${statePath}; pass --resume <path> to continue, ` +
        `or --state-file <other-path> for a fresh run`
      )
    }
    console.log('FRESH RUN — generating new WOTS+ keys')
    const pqCurrent = genWotsKeypair()
    const pqNext = genWotsKeypair()
    state = {
      vaultId: vaultIdNum.toString(),
      pqCurrent: serializeKeypair(pqCurrent),
      pqNext: serializeKeypair(pqNext),
    }
    saveState(state, statePath)
    console.log('STATE SAVED to', statePath)
    console.log('  vault id      :', state.vaultId)
    console.log('  pqCurrent.seed:', state.pqCurrent.publicSeed)
    console.log('  pqNext.seed   :', state.pqNext.publicSeed)
  }

  const secret = loadDeployerSecret()
  const xOnly = secp256k1.getPublicKey(secret, true).slice(1)
  const rpc = new RpcConnection(ARCH_RPC)
  const client = new QuipArchClient({ rpc, programId: programIdFor('testnet') })
  const deployerP2tr = btc.p2tr(xOnly, undefined, btc.TEST_NETWORK)
  const bip322 = makeBip322Signer(secret, deployerP2tr.address!, xOnly)
  const vaultId = createVaultId(BigInt(state.vaultId))
  const walletPDA = client.walletAddress(xOnly, vaultId)
  const walletBtcAddr = await withRetry('getAccountAddress(walletPDA)',
    () => rpc.getAccountAddress(walletPDA as Pubkey))
  const ownerBtcAddr = await withRetry('getAccountAddress(owner)',
    () => rpc.getAccountAddress(xOnly as Pubkey))

  console.log('deployer x-only:', toHex(xOnly))
  console.log('deployer P2TR  :', deployerP2tr.address)
  console.log('owner BTC addr :', ownerBtcAddr)
  console.log('wallet PDA hex :', toHex(walletPDA))
  console.log('wallet BTC addr:', walletBtcAddr)

  const ctx: Ctx = {
    rpc, client, secret, xOnly, bip322, deployerP2tr,
    ownerBtcAddr, walletPDA, walletBtcAddr, vaultId, statePath,
  }

  await ensureOwnerAnchored(ctx)
  await ensureFunding(ctx, state)
  await ensureWalletCreated(ctx, state)
  await ensureBtcTransferSubmitted(ctx, state)
  await waitForBtcTransferProcessed(ctx, state)
  await verifyRoundTrip(ctx, state)

  console.log('\nSMOKE BTC-TRANSFER PASS — non-anchor UTXO spent, BTC landed back at deployer, pq_owner rotated.')
  console.log('state file:', statePath)
}

main().catch((err) => {
  console.error('SMOKE TEST FAILED:', err)
  console.error('   resume with: npx tsx scripts/smoke-btc-transfer.ts --resume <state-file>')
  process.exit(1)
})
